export const COPY = {
  listTitle: 'Cuti Saya',
  listSubtitle: 'Kelola pengajuan cuti Anda',
  applyTitle: 'Ajukan Cuti',
  applySubtitle: 'Lengkapi formulir di bawah ini',
  detailTitle: 'Detail Cuti',
  apply: 'Ajukan',
  applyNew: 'Ajukan Cuti',
  applyAgain: 'Ajukan Ulang',
  viewDetail: 'Lihat Detail',
  cancel: 'Batalkan',
  back: 'Kembali',
  search: 'Cari',
  searchPlaceholder: 'Cari berdasarkan tipe atau alasan',
  filters: {
    all: 'Semua',
    pending: 'Menunggu',
    approved: 'Disetujui',
    rejected: 'Ditolak',
    cancelled: 'Dibatalkan',
  },
  quota: {
    title: 'Sisa Cuti',
    remaining: 'sisa',
    of: 'dari',
    unlimited: 'Tanpa batas',
    days: 'hari',
  },
  emptyList: {
    all: {
      title: 'Belum ada pengajuan cuti',
      subtitle: 'Mulai dengan mengajukan cuti pertama Anda.',
    },
    pending: {
      title: 'Tidak ada cuti menunggu',
      subtitle: 'Semua pengajuan Anda sudah diproses.',
    },
    approved: {
      title: 'Belum ada cuti disetujui',
      subtitle: 'Pengajuan yang disetujui akan muncul di sini.',
    },
    rejected: {
      title: 'Tidak ada cuti ditolak',
      subtitle: 'Semua pengajuan Anda berjalan lancar.',
    },
    cancelled: {
      title: 'Tidak ada cuti dibatalkan',
      subtitle: 'Pengajuan yang Anda batalkan akan muncul di sini.',
    },
  },
  steps: {
    type: 'Tipe Cuti',
    typeHint: 'Pilih jenis cuti yang akan diajukan',
    dates: 'Tanggal Cuti',
    datesHint: 'Tentukan rentang tanggal',
    reason: 'Alasan Cuti',
    reasonHint: 'Jelaskan alasan pengajuan Anda',
    attachment: 'Lampiran',
    attachmentHint: 'Unggah dokumen pendukung jika diperlukan',
  },
  fields: {
    startDate: 'Mulai',
    endDate: 'Selesai',
    totalDuration: 'Total Durasi',
    selectDate: 'Pilih tanggal',
    reasonPlaceholder: 'Tuliskan alasan cuti Anda di sini...',
    minReasonHint: (n: number) => `Tambah ${n} karakter lagi`,
    attachmentRequired: 'Wajib dilampirkan',
    attachmentOptional: 'Opsional',
    attachmentTypes: 'PDF, JPG, JPEG, atau PNG. Maks 5MB.',
    chooseFile: 'Pilih File',
    removeFile: 'Hapus',
    uploaded: 'Berhasil diunggah',
  },
  submit: 'Kirim Pengajuan',
  submitting: 'Mengirim...',
  uploading: 'Mengunggah...',
  detail: {
    requester: 'Pemohon',
    reason: 'Alasan',
    attachment: 'Lampiran',
    dateRange: 'Periode Cuti',
    approvalRoute: 'Alur Persetujuan',
    decisionNote: 'Catatan Keputusan',
    openAttachment: 'Buka',
    requestNo: 'Nomor Pengajuan',
    days: 'hari',
    waitingFor: (name: string) => `Menunggu persetujuan ${name}`,
    waitingForGeneric: 'Menunggu persetujuan atasan',
    approvedOn: 'Disetujui pada',
    rejectedOn: 'Ditolak pada',
    cancelledOn: 'Dibatalkan pada',
    noApprovals: 'Belum ada langkah persetujuan.',
    loading: 'Memuat detail cuti...',
    loadError: 'Gagal memuat detail cuti.',
    retryBtn: 'Coba Lagi',
    notFound: 'Cuti tidak ditemukan.',
    attachmentTapPreview: 'Ketuk untuk melihat',
    attachmentTapOpen: 'Ketuk untuk membuka di app lain',
    attachmentOpenError: 'Gagal membuka lampiran. Coba lagi nanti.',
    previewClose: 'Tutup',
  },
  stepper: {
    approved: 'Disetujui',
    rejected: 'Ditolak',
    waiting: 'Menunggu',
    notStarted: 'Belum dimulai',
  },
  cancelLoading: 'Membatalkan...',
  confirmCancel: {
    title: 'Batalkan Pengajuan?',
    message: 'Pengajuan cuti ini akan dibatalkan dan tidak dapat dikembalikan.',
    confirm: 'Ya, Batalkan',
    keep: 'Biarkan',
  },
  toasts: {
    cancelled: 'Pengajuan cuti berhasil dibatalkan.',
    submitted: 'Pengajuan cuti berhasil dikirim.',
  },
} as const;
